# Testing and linting the application

name: building and releasing the python package
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python all python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build tools
        run: pip install build twine

      - name: build the package
        run: python -m  build

      - name: Publish package on pypi.org
        run: |
          twine upload -u "__token__" -p "${{secrets.PYPI_TOKEN}}" dist/*