# Testing and linting the application

name: building python package
on:
  push:
    branches:
      - development

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python all python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install in editable mode
        run: 'pip install -e .[test]'

      - name: Lintint with flake8
        run: flake8 . --statistics

      - name: Type cheking with mypy
        run: mypy src/ tests/

      - name: Run Pytest
        run: 'pytest tests'
      
  build:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python all python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install build tools
        run: pip install build twine

      - name: Publish package on pypi.org
        run: |
          ls -la
          twine upload -u "__token__" -p "${{secrets.TEST_PYPI_TOKEN}}" --repository testpypi dist/*